version: '3.3'
networks:
    datapipeline:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "172.18.0.0/16"
services:
   spark-master:
      build:
        context: .
        dockerfile: DockerfileSpark
      links:
        - "db"
      ports:
        - "9000:8080"
        - "7077:7077"
      volumes:
        - ./appsspark:/opt/spark-apps
        - ./data:/opt/spark-data
      environment:
        - SPARK_LOCAL_IP=spark-master
        - SPARK_WORKLOAD=master
        - SPARK_DRIVER_MEMORY=1G
        - SPARK_EXECUTOR_MEMORY=1G
        - SPARK_MASTER_CORES=1
        - SPARK_MASTER=spark://spark-master:7077
        - SPARK_MASTER_MEMORY=1G
      networks:
        datapipeline:
            ipv4_address: 172.18.0.6
   extractionscript:
      build: .   
      links:
         - "db"
      networks:
         datapipeline:
            ipv4_address: 172.18.0.2
   db:
     container_name: mydb
     image: mysql:5.7
     ports:
       - "32001:3306"
     command: --init-file /data/application/init.sql
     volumes:
        - ./init.sql:/data/application/init.sql
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_ROOT_USER: root
       MYSQL_DATABASE: ggvd
       MYSQL_USER: root
       MYSQL_PASSWORD: root
     networks:
        datapipeline:
            ipv4_address: 172.18.0.7
   zookeeper:
     image: confluentinc/cp-zookeeper:latest
     environment:
       ZOOKEEPER_CLIENT_PORT: 2181
       ZOOKEEPER_TICK_TIME: 2000
     ports:
       - 2181:2181
     networks:
       datapipeline:
          ipv4_address: 172.18.0.3

   kafka:
     image: confluentinc/cp-kafka:latest
     depends_on:
       - zookeeper
     ports:
       - 9092:9092
     environment:
       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
       KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
       KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
       KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
       KAFKA_CREATE_TOPICS: "topic_test:1:1"
       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
       KAFKA_BROKER_ID: 1
     networks:
       datapipeline:
          ipv4_address: 172.18.0.5
